# VelocityBench Makefile
# Modular Makefile structure for better maintainability
# See make/*.mk for individual target implementations

# Include shared variables from all modules
include make/variables.mk

# Include all modular Makefiles
include make/blog.mk
include make/personas.mk
include make/comments.mk
include make/framework.mk
include make/quality.mk
include make/utils.mk

# Default target
.PHONY: help
help:
	@echo "======================================================================"
	@echo "VelocityBench - Framework Benchmarking Suite"
	@echo "======================================================================"
	@echo ""
	@echo "Blog Generation Commands:"
	@echo "  make blog-all                   - Generate ALL blog posts for all patterns"
	@echo "  make blog-fraisier              - Generate Fraisier deployment pattern blogs"
	@echo "  make blog-webhooks              - Generate webhook deployment blogs"
	@echo "  make blog-git-providers         - Generate Git provider abstraction blogs"
	@echo "  make blog-cqrs                  - Generate CQRS deployment pattern blogs"
	@echo "  make blog-history               - Generate deployment history blogs"
	@echo "  make blog-multi-provider        - Generate multi-Git-provider blogs"
	@echo "  make blog-multi-env             - Generate multi-environment blogs"
	@echo "  make blog-pattern PATTERN=<id>  - Generate single pattern blog"
	@echo "  make blog-list                  - List all discovered patterns"
	@echo "  make blog-clean                 - Clean generated blog files"
	@echo ""
	@echo "Comment & Persona Commands:"
	@echo "  make personas-test              - Test persona generation (10 personas)"
	@echo "  make personas-generate          - Generate ~2000 diverse personas"
	@echo "  make personas-validate          - Validate all personas (coherence check)"
	@echo "  make personas-validate-sample   - Validate first 100 personas"
	@echo "  make personas-correct           - Correct personas based on vLLM analysis"
	@echo "  make personas-correct-sample    - Correct first 50 personas (faster testing)"
	@echo "  make personas-correct-dry       - Analyze personas without corrections"
	@echo "  make personas-analyze           - Analyze generated personas"
	@echo "  make personas-clean             - Clean generated personas"
	@echo ""
	@echo "  make comments-test              - Test comment generation (5 posts)"
	@echo "  make comments-generate          - Generate comments on ALL blog posts"
	@echo "  make comments-replies           - Generate replies to debatable comments"
	@echo "  make comments-validate          - Validate/filter generated comments"
	@echo "  make comments-load              - Load comments to PostgreSQL database"
	@echo "  make comments-analyze           - Analyze generated comments"
	@echo "  make comments-clean             - Clean generated comment files"
	@echo ""
	@echo "Benchmark Commands:"
	@echo "  make up                         - Start all 8 benchmark frameworks (DATA_VOLUME=xs)"
	@echo "  make up-medium                  - Start with medium dataset (10K users)"
	@echo "  make down                       - Stop all benchmark frameworks"
	@echo "  make smoke-test                 - Health check all frameworks"
	@echo "  make parity-test                - Cross-framework data consistency test"
	@echo "  make n1-guard                   - N+1 query regression test (serial)"
	@echo "  make bench-one FRAMEWORK=<n>    - k6 benchmark a single framework"
	@echo "  make bench-all                  - Full k6 suite (all frameworks, ~90 min)"
	@echo "  make bench                      - FraiseQL v_* vs tv_* comparison"
	@echo "  make test-seed                  - Verify seed data row counts"
	@echo ""
	@echo "Framework Management Commands:"
	@echo "  make framework-list             - List all available frameworks"
	@echo "  make framework-start            - Start a framework (FRAMEWORK=<name>)"
	@echo "  make framework-stop             - Stop a framework (FRAMEWORK=<name>)"
	@echo "  make framework-smoke            - Run smoke tests on running frameworks"
	@echo ""
	@echo "Database Commands:"
	@echo "  make db-up                      - Start PostgreSQL database"
	@echo "  make db-down                    - Stop PostgreSQL database"
	@echo ""
	@echo "vLLM Server Commands:"
	@echo "  make vllm-start                 - Start vLLM server"
	@echo "  make vllm-status                - Check vLLM server status"
	@echo "  make vllm-stop                  - Stop vLLM server"
	@echo ""
	@echo "Virtual Environment Commands:"
	@echo "  make venv-setup                 - Create virtualenv if needed"
	@echo "  make venv-check                 - Check if virtualenv is set up"
	@echo "  make venv-info                  - Show virtualenv info"
	@echo ""
	@echo "Code Quality Commands:"
	@echo "  make lint                       - Lint Python code with ruff"
	@echo "  make format                     - Format Python code with ruff"
	@echo "  make type-check                 - Type-check Python code with ty"
	@echo "  make quality                    - Run all quality checks"
	@echo ""
	@echo "Examples:"
	@echo "  make personas-test              # Generate 10 test personas"
	@echo "  make comments-test              # Test comment generation on 5 posts"
	@echo "  make framework-start FRAMEWORK=strawberry"
	@echo "  make quality                    # Run all code quality checks"
	@echo ""
	@echo "======================================================================"
	@echo "For more details, see make/*.mk files or run: make <target>"
	@echo "======================================================================"
