play {
  http.secret.key = "changeme"
  http.secret.key = ${?APPLICATION_SECRET}

  server.http.port = 4000
  server.http.port = ${?PORT}
}

# Database configuration
db {
  host = "localhost"
  host = ${?DB_HOST}
  port = 5432
  port = ${?DB_PORT}
  name = "velocitybench_benchmark"
  name = ${?DB_NAME}
  user = "benchmark"
  user = ${?DB_USER}
  password = "benchmark123"
  password = ${?DB_PASSWORD}

  pool {
    minSize = 10
    maxSize = 50
  }
}
